import { Game } from "./Game";

export const games: Game[] = [
  {
    appid: 70,
    name: "Half-Life",
    company: "Valve",
    price: 20,
    releaseDate: "2004-05-01",
    genre: ["Horror", "Abenteuer", "Physik", "Survival"],
  },
  {
    appid: 1594320,
    name: "Captain of Industry",
    company: "Adobe",
    price: 40,
    releaseDate: "2014-09-26",
    genre: ["Abenteuer", "Simulation", "Aufbauspiel", "Robert hat Spaß"],
  },
  {
    appid: 2141910,
    name: "Magic: The Gathering Arena",
    company: "343 Studios",
    price: 14.99,
    releaseDate: "2007-07-07",
    genre: ["Simulation", "RPG", "MMO", "Abenteuer", "Survival"],
  },
  {
    appid: 480,
    name: "Spacewar",
    company: "Paradox Interactive",
    price: 40,
    releaseDate: "2008-08-07",
    genre: ["Krieg", "Weltraum", "Simulation", "MMO", "Aufbauspiel"],
  },
  {
    appid: 1091500,
    name: "Cyberpunk 2077",
    company: "CD Projekt Red",
    price: 50,
    releaseDate: "2020-11-21",
    genre: ["Cyberpunk", "Abenteuer", "Survival", "RPG", "Story", "Simulation"],
  },
  {
    appid: 1868180,
    name: " Etrian Odyssey HD",
    company: "RA Micro Software AG",
    price: 2.99,
    releaseDate: "2012-12-05",
    genre: [
      "Simulation",
      "Aufbauspiel",
      "Abenteuer",
      "Robert hat Spaß",
      "Story",
    ],
  },
  {
    appid: 730,
    name: "Counter-Strike: Global Offensive",
    company: "Valve",
    price: 0,
    releaseDate: "2016-06-25",
    genre: ["Krieg", "FPS", "Simulation", "Physik"],
  },
  {
    appid: 736260,
    name: "Baba Is You",
    company: "Adobe",
    price: 0,
    releaseDate: "2012-12-05",
    genre: ["Robert hat Spaß", "Abenteuer", "Simulation", "Story", "MMO"],
  },
  {
    appid: 1172380,
    name: "STAR WARS Jedi: Fallen Order™ ",
    company: "Respawn",
    price: 69.99,
    releaseDate: "2020-05-04",
    genre: ["Story", "Krieg", "Survival", "Physik", "RPG"],
  },
];
